Zh/eip effect chen
ethlibrary/EIPs pull request #28
Opened 2022-01-05 07:39 UTC by chenrui5199

### 翻译：EIP-x

- [ ] 翻译时参考过 [区块链术语 - by EthFans](https://github.com/editor-Ajian/List-of-translation-of-crypto-terms-by-EthFans/blob/under-finalized/Blockchain%20and%20Ethereum%20Terminology.md)
- [ ] 翻译时中英文标点准确

### 翻译参考链接：

2022-01-05 07:44 UTC, izayl commented on EIPS/eip-2384.md
>  ---
meta 信息只能修改 title 的内容，其他的不要做翻译和修改，系统会统一进行替换
```diff
---
eip: 2384
-title: Muir Glacier Difficulty Bomb Delay
+title: 缪尔冰川（Muir Glacier）难度炸弹推迟
author: Eric Conner (@econoar)
discussions-to: https://ethereum-magicians.org/t/eip-2384-difficulty-bomb-delay
type: Standards Track
category: Core
status: Final
created: 2019-11-20
---
```

2022-01-05 07:46 UTC, izayl commented on EIPS/eip-2384.md
> +由于难度炸弹（也被称为“_冰川时期_”）的缓慢加速，平均出块时间正在攀升。本次 EIP 提议将难度炸弹再推迟 400 万个区块（换算成时间单位，大约是 611 天）。
`攀升` => `增加`  may be better

2022-01-05 07:50 UTC, izayl commented on EIPS/zh/eip-210.md
> +将区块哈希存储在状态中，从而降低协议复杂性和处理区块哈希操作码所需的客户端实现复杂性。它还扩展了区块哈希检查的范围，其副作用(side effect)是在具有非常远的区块编号的区块之间创建直接链接，从而促进更高效的初始轻客户端同步。
使用中文括号

2022-01-05 07:51 UTC, izayl requested changes
👍🏻 赞，很多专有名词都标注了原文，感谢对 EIP  翻译的贡献

麻烦再看下 comments 里的小问题，改好后就 merge

2022-01-07 08:08 UTC, Riely007 requested changes
有两个小问题，需要修改一下～

2022-01-07 08:08 UTC, Riely007 commented on EIPS/eip-150.md
> +### 参考资料
元参考

2022-01-07 08:08 UTC, Riely007 commented on EIPS/eip-2384.md
> +## 理论基础
rationale = 基本原理

2022-01-07 08:52 UTC, Riely007 approved these changes

2022-01-07 08:54 UTC, merged